
services:

  tech_sup_bot:
    build:
      context: /home/kuiva/TechSupBot
      dockerfile: Dockerfile
    container_name: tech_sup_bot
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.tech_sup_bot.loadbalancer.server.port=${PORT_TECH_SUPP}"
      - "traefik.http.routers.tech_sup_bot.rule=Host(`${HOST_URL}`) && PathPrefix(`/callback/bot_tech_sup/update`)"
      - "traefik.http.routers.tech_sup_bot.entrypoints=websecure8"
      - "traefik.http.routers.tech_sup_bot.tls=true"
    environment:
      TECH_BOT_TOKEN: ${TECH_BOT_TOKEN}
      TECH_BOT_URL: ${TECH_BOT_URL}
      TECH_PORT_TECH_SUPP: ${PORT_TECH_SUPP:-8090}
      TECH_DATASOURCE_URL: ${TECH_DATASOURCE_URL}
      TECH_DATASOURCE_USERNAME: ${TECH_DATASOURCE_USERNAME}
      TECH_DATASOURCE_PASSWORD: ${TECH_DATASOURCE_PASSWORD}
      TECH_DATASOURCE_DRIVER_NAME: ${TECH_DATASOURCE_DRIVER_NAME}
    volumes:
      - ./.env:/app/.env
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - /home/kuiva/TechSupBot/redis.conf:/usr/local/etc/redis/redis.conf
      - /home/kuiva/TechSupBot/redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - my-network


  dispatcher:
    build:
      context: ./Dispatcher
      dockerfile: Dockerfile
    container_name: Dispatcher
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.dispatcher.loadbalancer.server.port=${PORT_DISPATCHER}"
      - "traefik.http.routers.dispatcher.rule=Host(`${HOST_URL}`) && PathPrefix(`/callback/bot_kpi/update`)"
      - "traefik.http.routers.dispatcher.entrypoints=websecure8"
      - "traefik.http.routers.dispatcher.tls=true"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_URL: ${BOT_URL}
      PORT_DISPATCHER: ${PORT_DISPATCHER:-8084}
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      DATASOURCE_DRIVER_NAME: ${DATASOURCE_DRIVER_NAME}
    volumes:
      - ./.env:/dispatcher/.env  # Копируем .env в /app
    networks:
      - my-network



  # Сервис PostgreSQL
  postgres:
    image: postgres:17.2
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-KPI_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATASOURCE_USERNAME} -d ${POSTGRES_DB} -h 127.0.0.1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    ports:
      - ${PORT_POSTGRES}:5432
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network


  traefik:
    container_name: traefik
    image: traefik:v2.9
    ports:
      - "80:80"
      - "443:443"  # Изменим на стандартный HTTPS порт
      - "9443:9443"  # Dashboard
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./tls.yml:/etc/traefik/tls.yml:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Монтируем всю директорию certbot
    labels:
      - "traefik.http.routers.traefik.rule=Host(`${HOST_URL}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure9"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8088"

      # Аутентификация для dashboard
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_PASSWORD}"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"

      # Redirect HTTP to HTTPS
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"  # Разрешаем API без TLS для внутреннего использования
      - "--entryPoints.web.address=:80"
      - "--entrypoints.websecure8.address=:443"
      - "--entrypoints.websecure9.address=:9443"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/tls.yml"
      # Включаем TLS с файловыми сертификатами
      - "--entrypoints.websecure.http.tls=true"


    restart: unless-stopped
    networks:
      - my-network
# Определение volumes
volumes:
  postgres_data:
    driver: local
  traefik-certs:
    driver: local

# Сеть
networks:
  my-network:
    driver: bridge