
services:
  # Сервис Dispatcher
  dispatcher:
    build:
      context: ./Dispatcher
      dockerfile: Dockerfile
    container_name: Dispatcher
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.dispatcher.loadbalancer.server.port=${PORT_DISPATCHER}"
      - "traefik.http.routers.dispatcher.rule=Host(`${HOST_URL}`) && PathPrefix(`/callback/update`)"
      - "traefik.http.routers.dispatcher.entrypoints=websecure8"
      - "traefik.http.routers.dispatcher.tls=true"
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      BOT_NAME: ${BOT_NAME}
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_URL: ${BOT_URL}
      PORT_DISPATCHER: ${PORT_DISPATCHER:-8084}
      KAFKA_PORT: ${KAFKA_PORT}
      KAFKA_HOSTNAME: ${KAFKA_HOSTNAME}
      KAFKA_KEY_SERIALIZER: ${KAFKA_KEY_SERIALIZER}
      KAFKA_VALUE_SERIALIZER: ${KAFKA_VALUE_SERIALIZER}
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      DATASOURCE_DRIVER_NAME: ${DATASOURCE_DRIVER_NAME}
    volumes:
      - ./.env:/dispatcher/.env  # Копируем .env в /app
      - /home/kuiva/Telegram-KPI-Bot/logs:dispatcher/logs
    networks:
      - my-network

  # Сервис GoogleSheetService
  googlesheetservice:
    build:
      context: ./GoogleSheetService
      dockerfile: Dockerfile
    container_name: GoogleSheetService
    restart: unless-stopped
    ports:
      - ${PORT_GOOGLESHEETS}:${PORT_GOOGLESHEETS}
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      PORT_GOOGLESHEETS: ${PORT_GOOGLESHEETS}
      CREDENTIALS_FILE_PATH: ${CREDENTIALS_FILE_PATH}
      KAFKA_PORT: ${KAFKA_PORT}
      KAFKA_HOSTNAME: ${KAFKA_HOSTNAME}
      SPREADSHEET_ID: ${SPREADSHEET_ID}
      DATASOURCE_URL: ${DATASOURCE_URL}
      DATASOURCE_USERNAME: ${DATASOURCE_USERNAME}
      DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      DATASOURCE_DRIVER_NAME: ${DATASOURCE_DRIVER_NAME}
    volumes:
      - ./.env:/app/.env  # Копируем .env в /app
      - /home/kuiva/Telegram-KPI-Bot/logs:/app/logs
    networks:
      - my-network

  # Сервис Kafka
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - ${KAFKA_PORT}:${KAFKA_PORT}
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=kuivamachineclusterid
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9091
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${KAFKA_HOSTNAME}:${KAFKA_PORT}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    volumes:
      - kafka_data:/bitnami/kafka  # Именованный volume для данных Kafka
    networks:
      - my-network

  # Сервис PostgreSQL
  postgres:
    image: postgres:17.2
    container_name: postgres
    environment:
      POSTGRES_USER: ${DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${DATASOURCE_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-KPI_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATASOURCE_USERNAME} -d ${POSTGRES_DB} -h 127.0.0.1" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    ports:
      - ${PORT_POSTGRES}:5432
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Именованный volume для данных PostgreSQL
    networks:
      - my-network


  traefik:
    container_name: traefik
    image: traefik:v2.9
    ports:
      - 80:80
      - 8443:8443
      - 9443:9443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./tls.yml:/etc/traefik/tls.yml
      - /home/kuiva/certs:/etc/traefik/certs
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.traefik.rule=Host(`${HOST_URL}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure9"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8088"

      # Установка пароля для входа в админку
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_USER}:${TRAEFIK_PASSWORD}"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"

      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=false"
    command:
      - "--api.dashboard=true"
      - "--ping=true"
      - "--ping.entrypoint=ping"
      - "--entryPoints.ping.address=:8888"
      - "--entryPoints.web.address=:80"
      - "--entrypoints.websecure8.address=:8443"
      - "--entrypoints.websecure9.address=:9443"
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/tls.yml"
    restart: unless-stopped
    networks:
      - my-network
# Определение volumes
volumes:
  kafka_data:
    driver: local
  postgres_data:
    driver: local
  dispatcher_logs:
    driver: local
  googlesheetservice_logs:
    driver: local
  traefik-certs:
    driver: local

# Сеть
networks:
  my-network:
    driver: bridge